version: '3'
services:
  auth-microservice:
    container_name: auth-microservice-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ".:/usr/src/app"
