version: '3'
services:
  mailer-microservice:
    container_name: mailer-microservice-container
    build:
      context: .
      dockerfile: Dockerfile
      target: 'dev'
    ports:
      - "3004:3004"
    env_file:
      - .env.developement
    volumes:
      - ".:/usr/src/app"
      - "/usr/src/app/node_modules"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    container_name: mysql-container-mailer
    image: mysql:latest
    ports:
      - "3309:3306"
    env_file:
      - .env.developement
    volumes:
      - ./mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

  redis:
    container_name: redis-container-mailer
    image: 'redis:latest'
    ports:
      - '6379:6379'
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
